# -*- coding: utf-8 -*-
"""Module01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Fm632b26syD1ZI8guY5PWRNUyP9ZW2y
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load raw dataset
df = pd.read_csv('Cost_of_Living_and_Income_Extended.csv')

#Clean dataset

#Verify no null values
df.isnull().sum()

#Verify no duplicates
df[df.duplicated()]

#Designate data columns to keep and apply to dataframe
columns_to_keep = ['Region','Country', 'Year','Cost_of_Living']
df = df[columns_to_keep]

#Reorganize the rows by country in alphabetical order, followed by year in ascending order
df_cleaned = df.sort_values(by=['Country', 'Year'], ascending=[True, True])

#Exploratory Analysis


#Calculate average cost of living per region
region_avg_cost = df_cleaned.groupby('Region')['Cost_of_Living'].mean().reset_index()

#Plot average cost of living per region
plt.figure(figsize=(10, 6))
sns.barplot(data=region_avg_cost, x='Region', y='Cost_of_Living')
plt.title('Average Cost of Living per Region')
plt.xlabel('Region')
plt.ylabel('Average Cost of Living')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Average Costs of living in each respective to region

#Create separate bar charts for each multi-country region
avg_cost_per_country = df_cleaned.groupby(['Region', 'Country'])['Cost_of_Living'].mean().reset_index()

#Plot each region in a separate bar plot
regions = avg_cost_per_country['Region'].unique()
for region in regions:
    region_data = avg_cost_per_country[avg_cost_per_country['Region'] == region]

    plt.figure(figsize=(8, 5))
    sns.barplot(data=region_data, x='Country', y='Cost_of_Living')
    plt.title(f'Average Cost of Living in {region}')
    plt.ylabel('Average Cost of Living')
    plt.xlabel('Country')
    plt.tight_layout()
    plt.show()

#Average Costs of living per country, ordered in descending order

avg_cost_by_country = avg_cost_per_country.sort_values(by='Cost_of_Living', ascending=False).reset_index(drop=True)
print(avg_cost_by_country)